<a href="https://colab.research.google.com/github/soon15/2025-1-A-myclass-BDA/blob/main/inclass/06w_A_mon_0414_easy_ch06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 단원 06-05 파생변수 추가

In [1]:
!git clone https://github.com/ai7dnn/data

Cloning into 'data'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 24 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (24/24), 2.14 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (4/4), done.

In [2]:
import pandas as pd
import numpy as np

exam = pd.read_csv('data/exam.csv')
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [3]:
# total 변수 추가
exam.assign(total = exam['math'] + exam['english'] + exam['science'])

    id  nclass  math  english  science  total
0    1       1    50       98       50    198
1    2       1    60       97       60    217
2    3       1    45       86       78    209
3    4       1    30       98       58    186
4    5       2    25       80       65    170
5    6       2    50       89       98    237
6    7       2    80       90       45    215
7    8       2    90       78       25    193
8    9       3    20       98       15    133
9   10       3    50       98       45    193
10  11       3    65       65       65    195
11  12       3    45       85       32    162
12  13       4    46       98       65    209
13  14       4    48       87       12    147
14  15       4    75       56       78    209
15  16       4    58       98       65    221
16  17       5    65       68       98    231
17  18       5    80       78       90    248
18  19       5    89       68       87    244
19  20       5    78       83       58    219

In [4]:
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [5]:
exam['total'] = exam['math'] + exam['english'] + exam['science']
exam.head(3)

   id  nclass  math  english  science  total
0   1       1    50       98       50    198
1   2       1    60       97       60    217
2   3       1    45       86       78    209

In [6]:
exam.assign(total = exam['math'] + exam['english'] + exam['science'],
            mean = (exam['math'] + exam['english'] + exam['science']) / 3)

    id  nclass  math  english  science  total       mean
0    1       1    50       98       50    198  66.000000
1    2       1    60       97       60    217  72.333333
2    3       1    45       86       78    209  69.666667
3    4       1    30       98       58    186  62.000000
4    5       2    25       80       65    170  56.666667
5    6       2    50       89       98    237  79.000000
6    7       2    80       90       45    215  71.666667
7    8       2    90       78       25    193  64.333333
8    9       3    20       98       15    133  44.333333
9   10       3    50       98       45    193  64.333333
10  11       3    65       65       65    195  65.000000
11  12       3    45       85       32    162  54.000000
12  13       4    46       98       65    209  69.666667
13  14       4    48       87       12    147  49.000000
14  15       4    75       56       78    209  69.666667
15  16       4    58       98       65    221  73.666667
16  17       5    65       68       98    231  77.000000
17  18       5    80       78       90    248  82.666667
18  19       5    89       68       87    244  81.333333
19  20       5    78       83       58    219  73.000000

In [7]:
exam.assign(test = np.where(exam.science >= 60, 'pass', 'fail'))

    id  nclass  math  english  science  total  test
0    1       1    50       98       50    198  fail
1    2       1    60       97       60    217  pass
2    3       1    45       86       78    209  pass
3    4       1    30       98       58    186  fail
4    5       2    25       80       65    170  pass
5    6       2    50       89       98    237  pass
6    7       2    80       90       45    215  fail
7    8       2    90       78       25    193  fail
8    9       3    20       98       15    133  fail
9   10       3    50       98       45    193  fail
10  11       3    65       65       65    195  pass
11  12       3    45       85       32    162  fail
12  13       4    46       98       65    209  pass
13  14       4    48       87       12    147  fail
14  15       4    75       56       78    209  pass
15  16       4    58       98       65    221  pass
16  17       5    65       68       98    231  pass
17  18       5    80       78       90    248  pass
18  19       5    89       68       87    244  pass
19  20       5    78       83       58    219  fail

In [8]:
exam = pd.read_csv('data/exam.csv')
exam.sample(frac=.3)

    id  nclass  math  english  science
1    2       1    60       97       60
4    5       2    25       80       65
11  12       3    45       85       32
9   10       3    50       98       45
8    9       3    20       98       15
15  16       4    58       98       65

In [9]:
exam.assign(total = exam.math + exam.english + exam.science).sort_values('total')

    id  nclass  math  english  science  total
8    9       3    20       98       15    133
13  14       4    48       87       12    147
11  12       3    45       85       32    162
4    5       2    25       80       65    170
3    4       1    30       98       58    186
9   10       3    50       98       45    193
7    8       2    90       78       25    193
10  11       3    65       65       65    195
0    1       1    50       98       50    198
12  13       4    46       98       65    209
14  15       4    75       56       78    209
2    3       1    45       86       78    209
6    7       2    80       90       45    215
1    2       1    60       97       60    217
19  20       5    78       83       58    219
15  16       4    58       98       65    221
16  17       5    65       68       98    231
5    6       2    50       89       98    237
18  19       5    89       68       87    244
17  18       5    80       78       90    248

In [10]:
exam.assign(total = exam.math + exam.english + exam.science).sort_values('total', ascending=False)

    id  nclass  math  english  science  total
17  18       5    80       78       90    248
18  19       5    89       68       87    244
5    6       2    50       89       98    237
16  17       5    65       68       98    231
15  16       4    58       98       65    221
19  20       5    78       83       58    219
1    2       1    60       97       60    217
6    7       2    80       90       45    215
14  15       4    75       56       78    209
12  13       4    46       98       65    209
2    3       1    45       86       78    209
0    1       1    50       98       50    198
10  11       3    65       65       65    195
7    8       2    90       78       25    193
9   10       3    50       98       45    193
3    4       1    30       98       58    186
4    5       2    25       80       65    170
11  12       3    45       85       32    162
13  14       4    48       87       12    147
8    9       3    20       98       15    133

In [11]:
exam.assign(total = exam['math'] + exam['english'] + exam['science'],
            mean = exam['total'] / 3)

KeyError: 'total'

In [ ]:
# 람다 함수
(lambda x, y: x + y)(15, 30)

In [ ]:
f = (lambda x, y: x + y)
f(15, 30)

In [ ]:
exam.assign(total = exam['math'] + exam['english'] + exam['science'],
            mean = lambda x: x['total'] / 3)

In [ ]:
exam.assign(total = exam['math'] + exam['english'] + exam['science'],
            mean = lambda x: x.total / 3)

In [ ]:
round(3.8976, 3)

In [ ]:
exam.assign(total = exam['math'] + exam['english'] + exam['science'],
            mean = lambda x: round(x.total / 3, 2))

In [ ]:
pd.set_option('display.precision', 3)

In [ ]:
exam.assign(total = exam['math'] + exam['english'] + exam['science'],
            mean = lambda x: x.total / 3)

In [ ]:
exam.assign(total = lambda d: d['math'] + d['english'] + d['science'],
            mean = lambda x: x.total / 3)

## df.agg() : 다양한 집계 연산을 수행

In [ ]:
exam = pd.read_csv('data/exam.csv')
exam.head()

In [ ]:
exam.agg("mean")

In [ ]:
exam.mean()

In [ ]:
exam.agg("mean")

In [ ]:
exam.agg(["mean"])

In [ ]:
exam.agg(["mean", 'median'])

In [ ]:
exam.agg(["mean", 'median'], axis=1)

In [ ]:
exam[['math', 'english', 'science']].agg(["mean", 'count'], axis=1)

In [ ]:
exam.agg(["mean", 'max', 'min', 'median'])

In [ ]:
exam.info()

In [ ]:
exam.describe()

In [ ]:
exam.agg(["mean", 'max', 'min', 'std', 'count', 'median'])

In [ ]:
exam.agg(mean_math = ('math', 'mean'))

In [ ]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, None, 10]],
                   columns=['A', 'B', 'C'])
df

In [ ]:
df.agg(["sum", 'mean', 'median', 'min', 'max', 'count'])

In [ ]:
df.agg(["sum", 'mean', 'median', 'min', 'max', 'count'], axis=0)

In [ ]:
df.agg(["sum", 'mean', 'median', 'min', 'max', 'count'], axis='index')

In [ ]:
df.agg(["sum", 'mean', 'median', 'min', 'max', 'count'], axis=1)

In [ ]:
df.agg(["sum", 'mean', 'median', 'min', 'max', 'count'], axis='columns')

In [ ]:
exam.sample(3)

In [ ]:
exam.groupby('nclass').agg(mean_math = ('math', 'mean'))

In [ ]:
exam.groupby('nclass').agg(max_math = ('math', 'max'))

In [ ]:
exam.groupby('nclass').agg('mean')

In [ ]:
exam.groupby('nclass').agg('mean')['math']

In [ ]:
exam.groupby('nclass').mean()

In [ ]:
exam.groupby('nclass').mean()['math']

In [ ]:
exam.groupby('nclass').mean()[['math', 'science']]

In [ ]:
df1 = exam.groupby('nclass').agg(['mean', 'median'])

In [ ]:
df1

In [ ]:
df1.columns

In [ ]:
exam.groupby('nclass').agg(mean_math = ('math', 'mean'),
                           mean_eng = ('english', 'mean'))

In [ ]:
exam.groupby('nclass').agg({'math': 'mean'})

In [ ]:
exam.groupby('nclass').agg({'math': 'mean', 'english': 'mean'})

In [ ]:
exam.groupby('nclass').agg({'math': 'mean', 'english': 'median'})

In [ ]:
exam.groupby('nclass').agg({'math': ['mean', 'min', 'max']})

In [ ]:
exam.groupby('nclass').agg({'math': ['mean', 'min', 'max'], 'science': ['mean', 'median', 'max']})

In [ ]:
exam.groupby('nclass').agg(mean_math = ('math', 'mean'))

In [ ]:
exam.groupby('nclass', as_index=True).agg(mean_math = ('math', 'mean'))

In [ ]:
exam.groupby('nclass', as_index=False).agg(mean_math = ('math', 'mean'))

## DataFrameGroupBy 알아보기

In [ ]:
exam.groupby('nclass')

In [ ]:
type(exam.groupby('nclass'))

In [ ]:
exam.groupby('nclass')

In [ ]:
range(5)

In [ ]:
list(range(5))

In [ ]:
d = list(exam.groupby('nclass'))

In [ ]:
len(d)

In [ ]:
d[1]

In [ ]:
d[1][0]

In [ ]:
d[1][1]

In [ ]:
for i in range(5):
  print(i, end=' ')

In [ ]:
for d in exam.groupby('nclass'):
  print(d, end='\n ============= \n')

In [ ]:
for n, df in exam.groupby('nclass'):
  print(n, '반')
  print('데이터프레임', '\n')
  print(df, end='\n' + '='*40 + '\n\n')

In [ ]:
exam.groupby('nclass').agg(mean_math   = ('math', 'mean'),
                           sum_math    = ('math', 'sum'),
                           median_math = ('math', 'median'),
                           count       = ('nclass', 'count'))

In [ ]:
exam.groupby('nclass').agg('count')

In [ ]:
exam.groupby('nclass').count()

## mpg 데이터 활용 groupby() agg()

In [ ]:
mpg = pd.read_csv('data/mpg.csv')
mpg.info()

In [ ]:
mpg.columns

In [ ]:
mpg.sample(frac=.02)

In [ ]:
mpg.groupby(['manufacturer']).agg(mean_cty = ('cty', 'mean'))

In [ ]:
mpg.groupby(['manufacturer', 'drv']).agg(mean_cty = ('cty', 'mean'))

In [ ]:
mpg.groupby(['drv', 'manufacturer']).agg(mean_cty = ('cty', 'mean'))

In [ ]:
mpg.groupby(['manufacturer', 'category']).agg(mean_cty = ('cty', 'mean'), mean_hwy = ('hwy', 'mean'))

In [ ]:
mpg.groupby(['category','manufacturer']).agg(mean_cty = ('cty', 'mean'), mean_hwy = ('hwy', 'mean'))

In [ ]:
mpg.query('manufacturer == "audi"').groupby(['drv']).agg(n = ('drv', 'count'))

In [ ]:
mpg.query('manufacturer == "honda"').groupby(['drv']).agg(n = ('drv', 'count'))

In [ ]:
mpg.query('manufacturer == "chevrolet"').groupby(['drv']).agg(n = ('drv', 'count'))

In [ ]:
mpg.query('manufacturer == "chevrolet"') \
   .groupby(['drv']) \
   .agg(n = ('drv', 'count'))

In [ ]:
mpg.query('manufacturer == "chevrolet"').groupby(['drv']).count()

In [ ]:
mpg.query('manufacturer == "chevrolet"').groupby(['drv']).count()[["model"]]

In [ ]:
df = mpg.query('manufacturer == "chevrolet"').groupby(['drv']).count()[["model"]]
df.rename(columns = {'model': 'n'}, inplace=True)
df

In [ ]:
mpg.query('manufacturer == "chevrolet"').groupby(['drv']).count()[["model"]] \
   .rename(columns = {'model': 'n'})

In [ ]:
mpg.groupby('drv').agg(n = ('drv', 'count'))

In [ ]:
mpg.groupby(['drv']).agg(n = ('drv', 'count'))

In [ ]:
mpg['drv'].value_counts()

In [ ]:
mpg[['drv', 'cyl']].value_counts()

In [ ]:
mpg.groupby(['drv', 'cyl']).agg('count')[["model"]]

In [ ]:
mpg[['drv', 'cyl']].value_counts().to_frame()

In [ ]:
mpg[['drv', 'cyl']].value_counts().to_frame().query('count > 40')

In [ ]:
mpg['drv'].value_counts().to_frame()

In [ ]:
mpg['drv'].value_counts().to_frame('n')

In [ ]:
mpg['drv'].value_counts().to_frame('n').rename_axis('drive')

In [ ]:
mpg.groupby('drv').agg(n = ('drv', 'count'))

In [ ]:
mpg.groupby('drv').agg(n = ('drv', 'count')).query('n > 100')

In [ ]:
mpg.query('category == "suv"') \
   .assign(total = (mpg.cty + mpg.hwy) / 2) \
   .groupby('manufacturer') \
   .agg(mean_total = ('total', 'mean')) \
   .sort_values('mean_total', ascending=False)

In [ ]:
mpg.query('category == "suv"') \
   .assign(total = (mpg.cty + mpg.hwy) / 2) \
   .groupby('manufacturer') \
   .agg(mean_total = ('total', 'mean')) \
   .sort_values('mean_total', ascending=False) \
   .head(5)

## 데이터 합치기

In [ ]:
# 중간고사 데이터 만들기
test1 = pd.DataFrame({'id'      : [1, 2, 3, 4, 5],
                      'mid' : [60, 80, 70, 90, 85]})

# 기말고사 데이터 만들기
test2 = pd.DataFrame({'id'    : [1, 2, 3, 4, 5],
                      'final' : [70, 83, 65, 95, 80]})

In [ ]:
test1

In [ ]:
test2

In [ ]:
pd.merge(test1, test2)

In [ ]:
pd.merge(test1, test2, on = 'id')

In [ ]:
pd.merge(test1, test2, on = 'id', how = 'inner')

In [ ]:
test1.merge(test2)

In [ ]:
test2.merge(test1)

In [ ]:
name = pd.DataFrame({'nclass'  : [1, 2, 3, 4, 5],
                     'teacher' : ['kim', 'lee', 'park', 'choi', 'jung']})
name

In [ ]:
exam.sample(3)

In [ ]:
pd.merge(exam, name)

In [ ]:
pd.merge(exam, name, on = 'nclass', how = 'inner')

In [ ]:
# 학생 1~5번 시험 데이터 만들기
group_a = pd.DataFrame({'id'   : [1, 2, 3, 4, 5],
                        'test' : [60, 80, 70, 90, 85]})

# 학생 6~10번 시험 데이터 만들기
group_b = pd.DataFrame({'id'   : [6, 7, 8, 9, 10],
                        'test' : [70, 83, 65, 95, 80]})

In [ ]:
group_a

In [ ]:
group_b

In [ ]:
pd.concat([group_a, group_b])

In [ ]:
pd.concat([group_a, group_b]).reset_index()

In [ ]:
pd.concat([group_a, group_b]).reset_index(drop=True)

In [ ]:
pd.concat([group_a, group_b]).reset_index(drop=True).shape[1]

## merge() 중간고사 예상 문제

In [ ]:
df1 = pd.DataFrame([[1, 'apple'], [2, 'banana']],
                  columns = ['id', 'fruits'])
df1

In [ ]:
df2 = pd.DataFrame([[1, 3000], [5, 500]],
                  columns = ['id', 'price'])
df2

In [ ]:
pd.merge(df1, df2)

In [ ]:
pd.merge(df1, df2, on = 'id', how='inner')

In [ ]:
df1.merge(df2, on = 'id', how='inner')

In [ ]:
pd.merge(df1, df2, on = 'id', how='left')

In [ ]:
df1.merge(df2, on = 'id', how='left')

In [ ]:
pd.merge(df1, df2, on = 'id', how='right')

In [ ]:
df1.merge(df2, on = 'id', how='right')

In [ ]:
pd.merge(df1, df2, how = 'cross')

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1.merge(df2, how = 'cross')

In [ ]:
df2.merge(df1, how = 'cross')

## 단원 06 종료